```{r setup, include=FALSE}
library(readr)
library(stringr)
library(knitr)
library(htmltools)
opts_chunk$set(echo = FALSE, warning = FALSE, 
               message = FALSE, fig.align = "center")
```

```{r read_in_metadata}
cran_meta <- read_csv("metadata/cran.csv")
github_meta <- read_csv("metadata/github.csv")
cran_preview_html <- sub('[.][^.]+$', '', list.files("outputs/html")) %>%
  str_split("-")

```
</div>
<div class="jumbotron">
<div class="container-fluid main-container">
<h2 class="text-center">Discover the best <strong>templates</strong> for your <strong class="text-primary">R Markdown</strong> documents</h2>
<div class="row" style="margin-top: 50px">
<div class="col-sm-2"></div>
<div class="col-sm-4">
<div class="text-justify">
<a href="gallery.html" class="btn btn-success btn-lg btn-block"><i class="fa fa-search"></i> Explore</a><br>
<p style="font-size: 18px;">Check out existing `r nrow(cran_meta)+nrow(github_meta)` R markdown templates on CRAN or github and browse some pre-rendered outputs in the <a href="gallery.html">gallery</a>. </p>
</div>
</div>
<div class="col-sm-4">
<div class="text-justify">
<a href="https://github.com/rmdtemplates/rmdtemplates.github.io/edit/master/metadata/github.csv" class="btn btn-info btn-lg btn-block"><i class="fa fa-pencil-square-o"></i> Contribute</a><br>
<p style="font-size: 18px;">Submit your github template package by modifying this list and fire a pull request. </p>
</div>
</div>

</div>
</div>
</div>

<div class="container-fluid main-container">


